export TERMINAL="kitty"
#export DISPLAY=":0"
export INTEL_DEBUG="noccs"
export PATH="/opt/flutter/bin:$PATH"
export ANDROID_HOME="$HOME/Personal/program/android/android-sdk"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
export XDG_CURRENT_DESKTOP="sway"
export FZF_DEFAULT_COMMAND='rg --hidden --no-ignore -l ""'
export EDITOR='helix'
export PATH=$PATH:/usr/local/go/bin
export QT_QPA_PLATFORMTHEME='qt5ct'
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
# export XDG_CURRENT_DESKTOP=SWAY
# export XDG_SESSION_DESKTOP=SWAY
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
# export XDG_MENU_PREFIX=arch- 
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
