alias search-history='history | rg '
alias rt-lck='sudo passwd -l root'
alias rt-unlck='sudo passwd -u root'
alias kill-tty='sudo pkill -9 -t '
alias sway-tree='swaymsg -t get_tree'
alias resolution='bash ~/scripts/resolution.sh'
alias float-window='$HOME/scripts/window.sh'
alias config='/usr/bin/git --git-dir="$HOME/.dotfiles/.git" --work-tree="$HOME/.dotfiles"'
alias ls='ls --color=auto --hyperlink=auto'
alias grep='grep --color=auto'
alias icat='kitten icat'
alias hx='helix'
alias dhistory='$HOME/scripts/dunstctl-history.sh'
alias cz='chezmoi'
alias repo-fast-idn='sudo reflector -f 5 --latest 20 -c Indonesia --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
alias pipthon='source /home/thinkpad/Program/python/env/bin/activate'
alias adb-connect='$HOME/scripts/adb-connect.sh'
alias led-off='echo "0 off" | sudo tee /proc/acpi/ibm/led 1> /dev/null; echo "10 off" | sudo tee /proc/acpi/ibm/led 1> /dev/null'
alias led-on='echo "0 on" | sudo tee /proc/acpi/ibm/led 1> /dev/null; echo "10 on" | sudo tee /proc/acpi/ibm/led 1> /dev/null'
alias yz='yazi'
alias kdefile='source ~/scripts/source/kdeconnect.sh'
alias kdefilesd='source ~/scripts/source/kdeconnectsdcard.sh'
alias sync-music='$HOME/scripts/rsync.sh'
# alias sshan='$HOME/scripts/sshan.sh'
alias tmux='tmux -2'
alias multipledir='$HOME/scripts/multipledir.sh'
alias extglob='shopt -s extglob'
alias cpr=$HOME/scripts/cp.sh
alias lsd='ls -ashx --group-directories-first'
alias m3u8-downloader='$HOME/scripts/m3u8-downloader.sh'
alias waydroid-desktop='$HOME/scripts/waydroid-desktop.sh'
alias hotspot='sudo $HOME/scripts/hotspot.sh --ap wlan0 access -p 123123123'
alias resfail='faillock --user $USER --reset'
alias clear-finger='sudo python $HOME/scripts/clear-finger.py'
alias grimshot="/usr/share/sway-contrib/grimshot"
alias pkill-all='$HOME/scripts/pkill.sh'
